include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
    no_leading_underscores_for_local_identifiers: ignore
    avoid_function_literals_in_foreach_calls: ignore
    camel_case_extensions: ignore
    camel_case_types: ignore
    non_constant_identifier_names: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
