import '_prelude_stub_gen_ffi.dart' as gen_ffi;

// - start prelude
// AUTO-GENERATED FILE, DO NOT MODIFY.
// Generated by cppcgen.
// ignore_for_file: unused_import, unused_element, camel_case_extensions, camel_case_types, non_constant_identifier_names

import 'dart:core';
import 'dart:core' as core show Duration;
import 'dart:ffi' as ffi;

import 'package:ffi/ffi.dart';
//ffigen-import

/// Hint to inline small functions (usually in extensions).
const _inline = pragma('vm:prefer-inline');

/// Helper class for FFI memory management.
sealed class FfiRef<T extends ffi.Pointer> implements ffi.Finalizable {
  FfiRef(this.ptr) {
    _attachFinalizer();
  }

  final T ptr;

  void _attachFinalizer();
  void _detachFinalizer();
}

class _FfiException extends Error {
  _FfiException(this.message, this.location);

  final String message;
  final String location;

  @override
  String toString() => 'FfiException at $location: $message';
}

/// A wrapper method to handle exceptions from FFI calls.
R _ffiCall<R>(R Function() fn) {
  final result = fn();
  final exception = gen_ffi.maybe_get_last_ffi_exception();

  if (exception != ffi.nullptr) {
    final message = exception.ref.message.cast<Utf8>().toDartString();
    final location = exception.ref.location.cast<Utf8>().toDartString();
    gen_ffi.ffi_exception_destroy(exception);

    throw _FfiException(message, location);
  }

  return result;
}