from typing import Any
from ..model import c, cpp
from ..dart import model as dart
from .generator import generate_enum, generate_class
from .. import utils
import logging

_logger = logging.getLogger('dart_generator')


def generate(entities: list[Any], prelude: list[str] = [], ffigen_file_name: str = '') -> str:
  code: list[list[str]] = []

  code.append([
    f'// AUTO-GENERATED FILE, DO NOT MODIFY.',
    f'// Generated by cppcgen.',
    f'',
    f'import \'dart:ffi\' as ffi;',
    f'import \'{ffigen_file_name}\' as gen_ffi;',
    f'',
    f'// Helper class for FFI memory management.',
    f'abstract class FfiRef<T extends ffi.Pointer> implements ffi.Finalizable {{',
    f'  FfiRef(this.ptr);',
    f'',
    f'  final T ptr;',
    f'',
    f'  void attachFinalizer();',
    f'  void detachFinalizer();',
    f'}}',
  ])

  code.append(prelude)

  for entity in entities:
    if isinstance(entity, cpp.Enum): code.append(dart.Enum(entity).generate())
    elif isinstance(entity, cpp.Structure): code.append(dart.Class(entity).generate())
    else:
      _logger.warning(f'Unsupported entity for Dart generation: {entity.full_name}')

  result_code: list[str] = []
  for part in code:
    result_code.extend(part)
    result_code.append('')

  return utils.code_list_to_str(result_code)
