#pragma once

// Generated by cppcgen. Do not edit manually.

#define EXPORT __attribute__((__visibility__("default"))) __attribute__((__used__))

#ifdef __cplusplus
  #define EXTERNC extern "C"
#else
  #define EXTERNC
#endif

#define FFI EXTERNC EXPORT

struct ffi_exception {
  const char* message;
  const char* location;
};

typedef ffi_exception* ffi_exception_t;

// Returns the last exception that occurred in FFI calls, or nullptr if none.
// If an exception is returned, the exception is transferred to the caller, and
// the internal exception storage is cleared.
ffi_exception_t maybe_get_last_ffi_exception();
void ffi_exception_destroy(ffi_exception* ex);
